'use strict'

/**
  The type of events generated by
  test runs.

  @readonly
  @enum {number}
*/
export var ObserverEventType = {
    /** The test has started. */
    eTestStart: 0,
    /**
      The test has completed and its result
      has been updated.
    */
    eTestEnd : 1
}
